---
- name: Create Server Group
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create a Server Group at CenturyLink Cloud
      clc_group:
        name: 'BDaas_test_group'
        parent: 'Default Group'
        state: present
      register: clc

    - name: debug
      debug: var=clc
