---

# installs servers

- name: Instantiate Master nodes
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy Master Nodes
      clc_server:
        name: RHEL
        password: Yahoo@123
        template: rhel-6-64
        count: 2
        cpu: 1
        memory: 2
        group: host_test
        state: present
      register: clc_data
    - name: debug
      debug: var=clc_data.servers
    - name: Create Data memory groups
      add_host:
        name={{item.ipaddress}}
        ansible_ssh_host={{ item.ipaddress }}
        ansible_ssh_user=root
        ansible_ssh_pass=Yahoo@123
        group=Data
      with_items: "{{clc_data[1].servers}}"
#    - debug: msg="{{groups['Data-Nodes']}}"
#    - name: instant var
#      vars:
#        mgmnt01: "{{groups['Data-Nodes']|first}}" 
#    - debug: var=mgmnt01
#    - debug: 
#       msg={% for host in groups['Data-Nodes'] %}{% set node = host %}{{node}}{{","}}{%- endfor -%}
    - debug: "{{ groups.Data }}"
