---

# installs servers

- name: Instantiate Master nodes
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy Master Nodes
      clc_server:
        name: MSTR
        template: redHat6-64
        count: 1
        cpu: 1
        memory: 2
        group: BdaaS_test
        state: present
        add_public_ip: true
        public_ip_ports:
          - 22
          - 80
        ttl: 345600
