---

# installs servers

- name: Instantiate Master nodes
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Deploy Master Nodes
      clc_server:
        name: RHEL
        password: Yahoo@123
        template: rhel-6-64
        count: 3
        cpu: 1
        memory: 2
        group: Ansible
        state: present
      register: clc_data
    - name: debug
      debug: var=clc_data.0.servers
    - name: Create Data memory groups
      add_host:
        name={{item.name}}
        ansible_ssh_host={{ item.ipaddress }}
        ansible_ssh_user=root
        ansible_ssh_pass=Yahoo@123
        groups=Data-Nodes
      with_flattened: "{{ clc_data.servers }}"
    - debug: msg="{{ hostvars[groups['Data-Nodes']] }}"      
#    - debug: "{{ groups.Data-Nodes }}"

